[features]
seeds = false
skip-lint = false
[programs.localnet]
governance_verifier = "ATCsJvzSbHaJj3a9uKTRHSoD8ZmWPfeC3sYxzcJJHTM5"

[provider]
cluster = "mainnet"
wallet = "/Users/brittcyr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

# Governance Program
[[test.validator.clone]]
address = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
[[test.validator.clone]]
address = "BZYjZ2ZbtAawP9WPt5yXszcoMWTvNFFX4AMbnDojtSGL"

# Governance
[[test.validator.clone]]
address = "Dg31swH4qLRzqgFsDZb3eME1QvwgAXnzA1Awtwgh3oc4"

# Proposal
[[test.validator.clone]]
address = "6ws4bv5CefMwVXi54fMc6c7VU1RrT3QxYYeGzQMiVp4Z"

# VoteRecordV2
[[test.validator.clone]]
address = "BsGL7UwBT9ojUTMgtYh6foZrbWVnJvBBpsprdjkswVA1"
