[features]
seeds = false
skip-lint = false
[programs.localnet]
governance_verifier = "ATCsJvzSbHaJj3a9uKTRHSoD8ZmWPfeC3sYxzcJJHTM5"

[provider]
cluster = "localnet"
wallet = "/Users/brittcyr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
